wandb_version: 1

cache_syn:
  value: 'True'
config:
  value: configs/eurosat.yaml
mmd_coeff:
  value: 0.01
shots:
  value: 16
train_batchsize:
  value: 128
train_epoch:
  value: 100
use_mmd:
  value: true
