# ------ root_path/dataset_name ------
#root_path: '/cis/net/io76a/data/aroy/imagenet/ILSVRC/Data'
#root_path: '/cis/net/io74a/data/ashah/datasets/imagenet/ILSVRC/Data'
#root_path: '/cis/net/io65a/data/ashah/Datasets/Imagenet/ILSVRC/Data'
root_path: '/cis/net/io91/data/aroy/imagenet/ILSVRC/Data'


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# load_cache: True
# load_pre_feat: True


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [7, 3]
search_step: [200, 20]

init_beta: 1
init_alpha: 1.17


# ------ Basic Config ------
dataset: 'imagenet'
shots: 4
backbone: 'RN50'

lr: 0.001
augment_epoch: 10
train_epoch: 20