wandb_version: 1

cache_syn:
  value: 'False'
config:
  value: configs/eurosat.yaml
mmd_coeff:
  value: 0.1
shots:
  value: 2
train_batchsize:
  value: 128
train_epoch:
  value: 100
use_mmd:
  value: true
